apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: miroplug
  name: miroplug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miroplug
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: miroplug
    spec:
      containers:
      - image: swiftbird/miroplug:latest
        name: miroplug
        ports:
          - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: miroplug
  name: miroplug
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: miroplug
